@startuml Lab2_1

(*) --> ===A1===
--> "Перенаправлення на сторінку з інструкцією"
--> ===A2===

===A1=== --> "Змінити мовних параметрів інтерфейсу системи"
--> ===A2===

===A1=== --> "Сортування позицій меню"

--> ===B1===
--> "За ціною"
if "" then
--> "Успіх1"
--> ===B2===
else
--> "Помилка1"
"Помилка1" --> ===B2===

===B1=== --> "За популярністю"
if "" then
--> "Успіх2"
--> ===B2===
else
--> "Помилка2"
"Помилка2" --> ===B2===

===B1=== --> "За категорією"
if "" then
--> "Успіх3"
--> ===B2===
else
--> "Помилка3"
--> ===B2===

--> ===A2===

===A1=== --> "Запит на створення замовлення"
if "" then
--> "Помилка4"
else
--> "Успіх4"
--> "Вибір місця"
--> ===C1===
--> "Змінити замовлення"
if "" then
--> "Помилка5"
else
--> "Успіх5"
--> "Запит на створення замовлення"

===C1=== --> "З собою"
if "" then
--> "Помилка6"
else
--> "Успіх6"
--> ===C2===

===C1=== --> "В закладі"
if "" then
--> "Помилка7"
else
--> "Успіх7"
--> ===C2===

--> "Оплата"
--> ===D1===
--> "Відмінити замовлення"

if "" then
--> "Помилка8"
else
--> "Успіх8"
--> "Перехід на головний екран"
--> ===A2===

===D1=== --> "Банківська карта"

if "" then
--> "Помилка9"
else
--> "Успіх9"

--> ===D2===

===D1=== --> "Готівка"

if "" then
--> "Помилка10"
else
--> "Успіх10"

--> ===D2===

--> "Оформлення замовлення"

--> ===A2===
--> (*)

@enduml