@startuml Lab2_1

(*) --> ===A1===
--> "Переглянути інструкцію використання терміналу"
--> ===A2===

===A1=== --> "Змінити мову інтерфейсу"
--> ===A2===

===A1=== --> "Створити замовлення"
if "" then
--> "Відсотрувати"
--> ===В1===
===В1=== --> "За ціною"
--> ===B2===
===В1=== --> "За категорією"
--> ===B2===
===В1=== --> "За популярністю"
--> ===B2===
--> ===A2===

else
--> "Обрати позиції"
--> "Вибір місця"

if "" then
--> "Змінити замовлення"
--> "Обрати позиції"

else
if "" then
--> "З собою"
else
--> "В закладі"

"З собою" --> "Оплата"
"В закладі" --> "Оплата"

if "" then
--> "Відмінити замовлення"
--> ===A2===
else
if "" then
--> "Готівка"
--> ===A2===
else
--> "Банківська карта"
--> ===A2===

--> (*)

@enduml