@startuml Lab3_1

actor "Клієнт" as CL

CL -> "Сервер" : Запит на зміну мови
activate "Сервер"
"Сервер" --> CL : Успішна зміна мови
deactivate "Сервер"

CL -> "Сервер" : Запит на отримання інструкції
activate "Сервер"
"Сервер" --> CL : Відкриття інструкції
deactivate "Сервер"

CL -> "Сервер" : Запит на сортування позицій меню
activate "Сервер"
"Сервер" --> CL : Отримання посортованих позицій меню
deactivate "Сервер"

CL -> "Сервер" : Відправка пакету вибраних позицій
activate "Сервер"
"Сервер" -> "Чек" : Запис замовлення
activate "Чек"
"Сервер" --> CL : Повідомлення про успішний запис замовлення
deactivate "Сервер"

CL -> "Сервер" : Відправка місця, яке обрав користувач
activate "Сервер"
"Сервер" -> "Чек" : Запис місця
"Сервер" --> CL : Повідомлення про успішний запис місця
deactivate "Сервер"

CL -> "Сервер" : Відправка способу оплати
activate "Сервер"
"Сервер" -> "Чек" : Запис способу оплати
"Сервер" --> CL : Повідомлення про успішний запис способу оплати
deactivate "Сервер"
deactivate "Чек"

"Сервер" -> "Чек" : Запит на надсилання замовлення персоналу
activate "Сервер"
activate "Чек"
actor "Персонал"
"Чек" -> "Персонал" : Надсилання чеку замовлення
activate "Персонал"
deactivate "Персонал"
"Чек" --> "Сервер" : Успішно надісланий чек
deactivate "Чек"
"Сервер" --> CL : Повідомлення про успішно створене замовлення
deactivate "Сервер"

@enduml